{
  description = "A Nix Flake auto-generated by Maru";

  inputs = {
    nixpkgs = { url = "github:nixos/nixpkgs/nixos-unstable"; };

  };

  outputs = inputs: {
    devShells.x86_64-linux.default = ({ nixpkgs, ... }:
      let pkgs = nixpkgs.legacyPackages.x86_64-linux;
      in with pkgs;
      pkgs.mkShell {
        buildInputs = [ ruby_3_2 rustc rustfmt rustup cargo ];
        inputsFrom = [ ];
        shellHook = "\n\n";
      }) inputs;
    formatter.x86_64-linux =
      ({ nixpkgs, ... }: with nixpkgs.legacyPackages.x86_64-linux; nixfmt)
      inputs;
  };
}
