{
  description = "A Nix Flake auto-generated by Maru";

  inputs = {
    nixpkgs = {
  url = "github:nixos/nixpkgs/nixos-unstable";
};

  };

  outputs = inputs: {
    devShells.aarch64-darwin.default = ({ nixpkgs, ... }:
  let
    pkgs = nixpkgs.legacyPackages.aarch64-darwin;
  in with pkgs; pkgs.mkShell {
    buildInputs = [ ruby_3_2 rustc rustfmt rustup cargo ];
    inputsFrom = [  ];
    shellHook = ''
      

    '';
  }
)
 inputs;
formatter.aarch64-darwin = ({ nixpkgs, ... }:
  with nixpkgs.legacyPackages.aarch64-darwin; nixfmt
)
 inputs;
  };
}
