module Maru
  module Nix
    class Flake
      def initialize(
        description: "A Nix Flake auto-generated by Maru",
        outputs:
      )
        @description = description
        @inputs = outputs.flat_map(&:dependencies).uniq(&:name)
        @outputs = outputs + [ default_formatter ]
      end

      def to_nix(system)
        <<~NIX
        {
          description = "#{@description}";

          inputs = {
            #{@inputs.map do |input|
              input.to_nix(system)
            end.join("\n")}
          };

          outputs = inputs: {
            #{@outputs.map do |output|
              output.to_nix(system) + " inputs;"
            end.join("\n")}
          };
        }
        NIX
      end

      private

      def default_formatter
        Maru::Nix::Formatter.new("nixfmt")
      end
    end
  end
end
