#!/usr/bin/env ruby --disable-gems

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

unshift_path = ->(path) {
  p = File.expand_path("../../#{path}", __FILE__)
  $LOAD_PATH.unshift(p) unless $LOAD_PATH.include?(p)
}
[ "cli-ui", "cli-kit", "sorbet-runtime" ].each do |vendor|
  unshift_path.call("vendor/deps/#{vendor}/lib")
end
unshift_path.call('lib')

require 'maru'

exit(Maru::ErrorHandler.call do
  Maru::EntryPoint.call(ARGV.dup)
end)
