module Rex
  module Nix
    class Flake
      def initialize(
        description: "A Nix Flake auto-generated by rex",
        inputs: [ Rex::Nix::Input.nixpkgs_unstable ],
        outputs:
      )
        @description = description
        @inputs = inputs
        @outputs = outputs
      end

      def to_nix(system)
        <<~NIX
        {
          description = "#{@description}";

          inputs = {
            #{@inputs.map do |input|
              input.to_nix(system)
            end.join("\n")}
          };

          outputs = { #{@inputs.map(&:name).join(", ")}, ... }:
          let
            pkgs = nixpkgs.legacyPackages.#{system};
          in {
            #{@outputs.map do |output|
              output.to_nix(system) + " pkgs"
            end.join("\n")}
          };
        }
        NIX
      end
    end
  end
end
